name: chasemarshall
favicon: null
layout_spectrum: 0.7635047801304609
typography_spectrum: 0.011681227246299386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6737806047312915
  lightness: 0.023836972657591105
  saturation: 0.9165040259249508
  rhythmicContrast: 0.5719764705281705
purpose: []
